feat: notifications
czaja307/PlannTer pull request #30
Opened 2024-12-16 22:52 UTC by czaja307

2024-12-17 18:04 UTC, simplyNoOne reviewed
good job overall, notifications look great

2024-12-17 18:04 UTC, simplyNoOne commented on PlannTer/Backend/Models/PlantModel.swift
> +            dispatchNotification(identifier: self.id.description, title: self.name + " is thirsty!", body: "Your plant needs to drink some water.", date: nextWateringDate)
it seems that you only dispatch the notification once the plant already was watered once, but what about just after creating it? add dispatching the notification after the plant was created as well

2024-12-18 19:20 UTC, simplyNoOne requested changes
okey, imma be annoying - you cannot dispatch notifications from a constructor: during the editing and saving we are gonna create a shitload of temporary plants that will never be saved to the database and we do NOT want any notifications for them. This way, said notifications will be created. Rather, add the caling of this method somewhere in the frontend, preferably, as an action happening on pressing the save button. It would be better if we had a way to cancel dispatch, so that when user changes the next watering date or a watering interval, the obsolete notification doesn't get sent, but if it's too much trouble, just leave it as is, but don't create notofications for the temp plants

2024-12-18 20:50 UTC, czaja307 commented
> okey, imma be annoying - you cannot dispatch notifications from a constructor: during the editing and saving we are gonna create a shitload of temporary plants that will never be saved to the database and we do NOT want any notifications for them. This way, said notifications will be created. Rather, add the caling of this method somewhere in the frontend, preferably, as an action happening on pressing the save button. It would be better if we had a way to cancel dispatch, so that when user changes the next watering date or a watering interval, the obsolete notification doesn't get sent, but if it's too much trouble, just leave it as is, but don't create notofications for the temp plants

dw, reviews are perfect excuse to be annoying
you're absolutely right about this, i didn't thought of temp plants
i'm not sure if handling notifications on frontend is a good practice, but this project is probably swift antipattern by now :p
as for the canceling notifications, i think i already handled that (there can be only one notification for each plant), but maybe i don't see something

gj with reviews, i just hope the next one will get accepted haha

2024-12-18 20:51 UTC, czaja307 commented on PlannTer/Notifications.swift
> +    notificationCenter.removePendingNotificationRequests(withIdentifiers: [identifier])
@simplyNoOne this should do the work, i suppose

2024-12-19 07:58 UTC, simplyNoOne approved these changes
good job

2024-12-19 07:59 UTC, merged